language: python
python:
  - "2.7"


# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install g++
  - pip install pytest coveralls
  - pip install --only-binary=numpy numpy
  - pip install -r requirements.txt
  - pip install .

# command to install dependencies
script:
  - python setup.py test

compiler: clang

# Run code coverage
after_success: coveralls

# Run on dev and master branches
branches:
  only:
    - master
