language: python
python:
  - "2.7"


# command to install dependencies
install:
  - sudo apt-get update -qq
  - pip uninstall pytest
  - pip install pytest==3.3 astropy==2.0
  - pip install -r requirements.txt
  - pip install .

# command to install dependencies
script:
  - python setup.py test

# Run code coverage
after_success: coveralls

# Run on dev and master branches
branches:
  only:
    - master
